export const SELECTED_FRIEND_DETAILS_REQUEST = "SELECTED_FRIEND_DETAILS_REQUEST";
export const SELECTED_FRIEND_DETAILS_SUCCESS = "SELECTED_FRIEND_DETAILS_SUCCESS";
export const SELECTED_FRIEND_DETAILS_FAIL = "SELECTED_FRIEND_DETAILS_FAIL";


export const GET_ALL_FRIENDS_DETAILS_REQUEST = "GET_ALL_FRIENDS_DETAILS_REQUEST";
export const GET_ALL_FRIENDS_DETAILS_SUCCESS = "GET_ALL_FRIENDS_DETAILS_SUCCESS";
export const GET_ALL_FRIENDS_DETAILS_FAIL = "GET_ALL_FRIENDS_DETAILS_FAIL";


export const NEW_INCOMING_MESSAGE_TRUE = "NEW_INCOMING_MESSAGE_TRUE";
export const NEW_INCOMING_MESSAGE_FALSE = "NEW_INCOMING_MESSAGE_FALSE";


export const CLEAR_ERRORS = "CLEAR_ERRORS";