export const NEW_MESSAGE_RECEIVED = "NEW_MESSAGE_RECEIVED";

export const IS_SUBSCRIBED = "IS_SUBSCRIBED";

export const GET_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_ALL_MESSAGES_FAIL";

export const ADD_TO_CURRENT_CHAT_MESSAGES = "ADD_TO_CURRENT_CHAT_MESSAGES";

export const CLEAR_ERRORS = "CLEAR_ERRORS";