export const GET_FRIEND_REQUESTS_REQUEST = "GET_FRIEND_REQUESTS_REQUEST";
export const GET_FRIEND_REQUESTS_SUCCESS = "GET_FRIEND_REQUESTS_SUCCESS";
export const GET_FRIEND_REQUESTS_FAIL = "GET_FRIEND_REQUESTS_FAIL";

export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";

export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";

export const UNSEND_FRIEND_REQUEST = "UNSEND_FRIEND_REQUEST";

export const GET_SENT_FRIEND_REQUESTS_REQUEST = "GET_SENT_FRIEND_REQUESTS_REQUEST";
export const GET_SENT_FRIEND_REQUESTS_SUCCESS = "GET_SENT_FRIEND_REQUESTS_SUCCESS";
export const GET_SENT_FRIEND_REQUESTS_FAIL = "GET_SENT_FRIEND_REQUESTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";